This contains the code required to practise broadcasting using python and numpy.

In [2]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
cal = A.sum(axis=0)

#this gives the vertical sum of columns of each column and outputs a row vector (matrix)
#to get the horizontal sums (row sums), use axis = 1

print(cal)

[12 15 18]


In [9]:
percentage = 100*A/(cal.reshape(1,3))

#reshaping was not required as cal matrix is already a 1,3 matrix
#100 is addede to convert the number into a percentage

print(percentage)

[[ 8.33333333 13.33333333 16.66666667]
 [33.33333333 33.33333333 33.33333333]
 [58.33333333 53.33333333 50.        ]]
